version: 0.2
env:
  variables:
    APP_NAME: "simon-game"
phases:
  install:
    runtime-versions:
      nodejs: 16.x
    commands:
      - echo install process started
      - npm install && npm install -g @angular/cli
  build:
    commands:
      - echo build process started now
      - ng build
  post_build:
    commands:
      - cd dist/simon-game
      - ls -la
      - aws s3 sync . s3://simon-game-frontend --delete
artifacts:
  files:
    - "**/*"
  base-directory: "dist*"
  discard-paths: yes
